### PR TITLE
ImGUI GL ES 2.0 fixes

### PR DESCRIPTION
**Pull request by gleblebedev**

### CODE REVIEW

**Comment by rokups** [comment]
Did you figure out root cause of this issue? AFAIK we should not be trying to maintain some kind of state between frames or even between executions of different middleware.

**Comment by rokups** [comment]
I dont think we should merge this. Omar was not excited about merging this upstream. Patching imgui will increase maintenance burden further. We could do this in SystemUI.cpp though.

**Comment by gleblebedev** [comment]
I can keep it in my branch, otherwise it doesn't compile. If it compiles for you then it's not a problem I guess?

**Comment by rokups** [comment]
Not sure what exactly does not compile 👀

**Pull request closed without merging**
