### PR TITLE
Compute Shader

### PR DESCRIPTION
**Pull request by JSandusky**
Implementation of a ComputeDevice for D3D11 and GL. This P/R isn't expected to actually make it in. It's largely for review purposes to call out anything serious or deemed lacking.

The ComputeDevice is a subsystem dependent on graphics and is expected to be used directly for specific tasks and not as a general purpose tool (it's not like a *Material*, it's a common API). Expected to be usable from handlers of any Graphics event that's at a clean mess-with-state safe segue.

Target Functionality:

- Read textures conventionally
- CBuffers
- Write textures (RWTexture2D / image2d)

DX11 has been tested to work as expected, GL has not yet been tested (though it's expected to be very very close) and there's likely build failures under different permutations of GL/D3D9. While DX11's implementation is fairly clean, GL is a bit nasty given the CBuffer and glShaderProgram handling that requires the ComputeDevice to stick its' nose into GraphicsImpl, otherwise there's potential side-effects from *bad* buffer/texture bindings.

Largest holes at present are in reflection of shader-parameters. DX11 doesn't reflect UAVs or sans-sampler-textures (that's a general problem w/ Urho shaders, ie. HLSL Object.Load only usage) and OpenGL reflects nothing presently because ShaderProgram is a mess with VS specific nastiness so a heavy refactor is needed first.

I'd like to get writing to general buffers (VBOs, IBOs, etc) in there but that's pretty nasty on DX11 (DXGI_FORMAT and MISC_UNSTRUCTURED headaches) so I doubt it'd make it into a first proper P/R.

### CODE REVIEW

**Comment by JSandusky** [comment]
CSharp usage:

```c#
// getting the shader like this is bad, need to fix
Shader computeShader = Context.Cache.GetResource<Shader>("Compute/HLSL/Test_Filter.hlsl");
ShaderVariation computeKernel = computeShader.GetVariation(ShaderType.Cs, "");

Texture2D rampTexture = Context.Cache.GetResource<Texture2D>("Textures/Spot.png");

Texture2D tex2D = new Texture2D(Context);
tex2D.SetSize(64,64, Graphics.GetRGBAFormat());

ComputeDevice cd = Context.GetSubsystem<ComputeDevice>();
cd.SetReadTexture(rampTexture, 0);
cd.SetWriteTexture(tex2D, 0 /*register*/, 0 /*face|layer*/, 0 /*mip-level*/);
cd.SetProgram(computeKernel);
cd.Dispatch(64, 64, 1);
tex2D.GetImage().SavePNG("CSTest_HalfDimFilter.png");
```

One of the HLSL testing crude filter compute shader (tests WIP):
```
/*
    Trivial filtering example that just dims the input by 50%
*/

#define DIM 64.0

Texture2D srcTex : register(t0);

RWTexture2D<float4> outputTexture : register(u0);

[numthreads(8,8,1)]
void CS(uint3 dispatchThreadId : SV_DispatchThreadID)
{
    float2 uvCoords = float2(dispatchThreadId.x, dispatchThreadId.y) / DIM;
    float4 pixel = srcTex.Load(int3(dispatchThreadId.xy, 0));
    
    pixel.rgb *= 0.5;
    
    outputTexture[dispatchThreadId.xy] = pixel;
}
```

**Comment by JSandusky** [comment]
There should be no difference between static/dynamic MacOS clang so I assume that's just a timeout error.

**Comment by rokups** [comment]
Random CI fluke, right. Restarted failed job and it succeeded.

**Comment by JSandusky** [comment]
This should be fine to merge whenever you want to. The major bits are dealt with and I'll submit smaller PRs for the buffer related parts and to clean things up.

**Comment by rokups** [comment]
Hmm something happened when you rebased. PR commit history has commits from master listed as changes :eyes:

**Comment by JSandusky** [comment]
Yeah, I'm going to go have cherry-pick into a clean branch and resubmit from a clean branch.

**Pull request closed without merging**
