### PR TITLE
OpenAL integration

### PR DESCRIPTION
**Pull request by tatjam**
I'm creating the pull request to get some feedback as I develop the integration. (And also, to see if it's a change well received by the rbfx developers)

OpenAL offers very high quality 3D audio, including effects such as reverb or HRTF.

I'm implementing it alongside Urho3D's default Audio module so it's backwards compatible, but I may add some new functions later on to control effects.

### CODE REVIEW

**Comment by tatjam** [comment]
I'm moving the pull request from draft to review, but OpenAL is not yet integrated into the build system

**Comment by rokups** [comment]
In coming days ill make a branch with OpenAL integrated for you, then you can rebase on it. Should i use https://github.com/kcat/openal-soft or some other repo?

**Comment by tatjam** [comment]
Yep, that's the official repo

**Comment by tatjam** [comment]
I just realized I did something wrong with git while trying to sync the fork, for some reason all my commits have been duplicated. Hope it's not a problem.

**Comment by rokups** [comment]
Make a new branch, cherry-pick commits you want from old one and force-push into your PR branch. That will fix weird stuff.

**Comment by tatjam** [comment]
I'll close this pull request and re-open it with my `openal` branch as a head

**Pull request closed without merging**
