### PR TITLE
fixed-icons-size

### PR DESCRIPTION
**Pull request by MonkeyFirst**
I've take a look on editor, and find what icons very big. So this little fix for this.

### CODE REVIEW

**Comment by rokups** [comment]
Thank you for taking your time to submit a PR 👍 However i do not think we should do this. We had uniform icon sizes previously. It breaks spectacularly in big scenes where many of such icons are present, especially when objects are close to one another. Could you make a screenshot without a fix? I wonder how big they are that they prompted a fix.

Icons have other problems though. In 2D mode they are actually quite small and panning skews them.

**Comment by MonkeyFirst** [comment]
Without fixing size, icons looks like this
icons

**Comment by eugeneko** [comment]
Maybe Editor should look at DPI here?

**Comment by rokups** [comment]
@MonkeyFirst whats your screen resolution?

**Comment by MonkeyFirst** [comment]
4К but I set 150% scale in win10 settings, without this scale all looks very smallest on screen.

**Comment by rokups** [comment]
@MonkeyFirst could you test latest master and see if issue is resolved?

**Comment by MonkeyFirst** [comment]
sure, here is picture
editor
I think it's looks the same

**Comment by rokups** [comment]
Could you select light/camera? It is hard to tell how far they are from editor camera. Maybe you are very close to them..? Saying this because i tested my patch on wife's PC which also has 4k monitor with extra scaling and icons looked ok to me.

**Comment by MonkeyFirst** [comment]
Extra scaling do not affect on veiwport's stuff at all, only on editor's UI.
here is a new picture with selected light
editor2

**Comment by rokups** [comment]
I am deferring fix for this for bit later. I will be working on HDPI handling in imgui and that is pretty closely tied to this issue. Once HDPI support is worked out it will be clear how we can tackle this issue.

**Pull request closed without merging**
