### PR TITLE
Fix Editor crash on Linux when opening a project

### PR DESCRIPTION
**Pull request by Mike3D**

### CODE REVIEW

**Comment by rokups** [comment]
Thanks for the PR, but it is not correct. Code below now does pointer comparison instead of string comparison. Also i do not see why this should be crashing, as `std::string` would make a copy of returned env variable. Whats the actual crash?

**Comment by Mike3D** [comment]
This is the crash report:

terminate called after throwing an instance of 'std::logic_error'
what(): basic_string::M_construct null not valid

**Comment by rokups** [comment]
Ah, the right fix would be to check if result of getenv is null, and assign 
it to std::string only when it isn't

**Comment by Mike3D** [comment]
Sure, a null check can do the job.

**Pull request closed without merging**
