### PR TITLE
Logger Resolve Changes

### PR DESCRIPTION
**Pull request by TrevorCash**
resolve logger object using "" as default logger if first attempt failed.

### CODE REVIEW

**Comment by TrevorCash** [comment]
I'm putting this PR up because logging was not working from plugins.  On my setup using "main" as the actual name was not getting the default logger, So I added a resolve to "" in case the first attempt failed.

**Comment by rokups** [comment]
Can you confirm whether this happens when `logInstance` is null?

**Comment by TrevorCash** [comment]
Yes it is null when it happens. also it only happens with BUILD_SHARED_LIBS=OFF

**Comment by rokups** [comment]
I pushed a proper fix. The core issue was you mixing dll plugins in static build (not sure how that happens, maybe it is another issue as it should not be possible) and `logInstance` was not initialized in plugin dlls. Then a broken logic in that function failed to create a logger in that case. Now loggers are always created and mutex locking is only done when `logInstance` is available. It should be fine as user is not expected to run any concurrent code with logging before engine initializes.

**Comment by TrevorCash** [comment]
I think the setup I had was that BUILD_SHARED_LIBS was not set and was off by default.  that made Urho3D build static.  but in my cmake list files I link to other libs specifying SHARED as the link type.  so TechGame linked to Urho3D(static) and all the other plugins dynamically.

**Comment by rokups** [comment]
I see. Plugin targets now shouldn't specify static or shared type so they 
build as proper kind automatically

**Comment by TrevorCash** [comment]
Got it, I've removed the SHARED specifier from all my plugins.

**Pull request closed without merging**
