### PR TITLE
Fix incorrect logger re-initialization.

### PR DESCRIPTION
**Pull request by eugeneko**
@rokups please look at this just in case I messed up

### CODE REVIEW

**Comment by rokups** [comment]
Did this cause any issues?

Also will `CreateCompleteTestContext()` reusable? Seems like it's scope is very narrow, not worthy of extra file 👀

**Comment by eugeneko** [comment]
@rokups I wouldn't have fixed it if it didn't cause any issues :trollface: 
Logger crashes if created twice, which is quite severe issue for tests.

> Also will CreateCompleteTestContext() reusable?

I am using it in other tests locally. Why do you think its scope is narrow? It spawns context usable by all Urho classes.

**Comment by rokups** [comment]
It also spawns engine instance and initializes it with hardcoded parameters. I am pretty sure some test will eventually need to change those parameters.

**Comment by eugeneko** [comment]
@rokups these params are good enough defaults, and we can always extend this function later.

This function is supposed to be "give me the context as if I'm in running application"
Which may be suboptimal, but it's the most reliable way to make sure code in UTs and in apps is run in similar conditions

**Pull request merged**
