### PR TITLE
Fix ParseAgurments Not including last character of last argument.

### PR DESCRIPTION
**Pull request by TrevorCash**

### CODE REVIEW

**Comment by rokups** [comment]
Didn't we have this fixed already? Can you provide reproduction instructions? I use command line parame all the time and have not bumped into this issue again.

**Comment by TrevorCash** [comment]
I thought we did too.  

On windows this command line:
`C:/Users/casht/Repos/greatgame/build/bin/Debug/AssetImporter.exe model ./TechnicSample.obj ./TechnicSample.mdl`

Will produce "TechnicSample.md" and not "TechnicSample.mdl"

**Comment by TrevorCash** [comment]
The first fix we did fixed the crash

**Comment by rokups** [comment]
I will test tomorrow, thanks. Ideally all tools should migrate to using 
CLI11 like engine does now.

**Comment by rokups** [comment]
Seems like i broke it in bb9adbd54622977cc1bf4f63e83f79551ecae9ea. Thanks!

**Pull request merged**
