### PR TITLE
modernized core, much faster, many other improvements

### PR DESCRIPTION
**Pull request by nem0**

### CODE REVIEW

**Comment by bvanevery** [comment]
Enables the future-looking LuaJIT.  Outstanding.

**Comment by nem0** [comment]
Lua scripting is optional plugin to attract more urho users

**Comment by rokups** [comment]
Wont merge because this is not godot.

**Comment by nem0** [comment]
I fixed that, please reopen

**Comment by bvanevery** [comment]
Reopen Source is the best kind of source.

**Pull request closed without merging**
