### PR TITLE
Add AddFrame() to DebugRenderer to make visualizing transformations easier.

### PR DESCRIPTION
**Pull request by TrevorCash**

### CODE REVIEW

**Comment by rokups** [comment]
Maybe AddAxis() would be more intuitive name? @eugeneko what do you think?

**Comment by TrevorCash** [comment]
That's kind of confusing to me.  Because sometimes Axis can refer to a line in 3D space where rotation about the line is free.  Whereas we are talking about a fully fixed coordinate frame.

**Comment by TrevorCash** [comment]
Hey Thanks :)

**Comment by rokups** [comment]
Sorry for being nitpicky and taking forever ^_^

**Pull request merged**
