### PR TITLE
Add IsNan() and IsInf() to Matrix Classes.

### PR DESCRIPTION
**Pull request by TrevorCash**
provides a simple mechanism for checking bad matrix formulation.

### CODE REVIEW

**Comment by rokups** [comment]
You lost vector bit though :)

**Comment by TrevorCash** [comment]
vector bit? can you elaborate?

**Comment by rokups** [comment]
Didn't you add IsNan to some vector class too?

**Comment by TrevorCash** [comment]
yes: https://github.com/rokups/rbfx/pull/118

**Comment by rokups** [comment]
Oh other PR right. Maybe add it to this one so we can merge?

**Pull request closed without merging**
